# Generated by Django 4.2.10 on 2024-02-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Salary'),
        ),
    ]
