# Generated by Django 4.2.10 on 2024-03-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Backend Developer'), (2, 'Frontend Developer'), (3, 'Full-stack Developer'), (4, 'DevOps Engineer'), (5, 'UI/UX Designer'), (6, 'QA Engineer'), (7, 'Project Manager')], null=True),
        ),
    ]
