# Generated by Django 4.2.10 on 2024-03-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashed_email_gravatar',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
