# Generated by Django 4.2.10 on 2024-03-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='position',
        ),
    ]
