# Generated by Django 4.2.10 on 2024-03-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_role_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
